projectdiscovery/katana

README.md
cmd/katana/main.go
internal/runner/options.go
pkg/engine/hybrid/hybrid.go
pkg/types/options.go
pkg/types/options_test.go

Context: #131.
```
sudo /home/edoardottt/go/bin/katana -hl -u http://edoardottt.com
[sudo] password for edoardottt: 
/_/\_\\_,_/\__/\_,_/_//_/\_,_/ v0.0.1							 
[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[FTL] could not create runner: could not create standard crawler: [launcher] Failed to get the debug url: [1107/180405.382126:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
This PR adds two flags as suggested:
```
-hoa, -headless-optional-arguments string[]  pass optional arguments to chrome
-hns, …
```

Headless issue with root user

---

cmd/katana/main.go

Closes #137
This will add a check to `main.go` if the version option is set to not return a fatal error message in that case.

Do not return error message in case of returning version

---

SECURITY.md
pkg/engine/hybrid/hybrid.go

Fixes #166 
Automatically pass proxy-server argument to chromium when both `-hl` and `-proxy` are set

Fixes #166

---

pkg/utils/extensions/extensions.go

- filter extensions 
`./katana -u https://www.youtube.com/ads/ -d 1 -ef js,css`
- match extensions
`./katana -u https://www.youtube.com/ads/ -d 1 -em js,css`

Parse the url and remove query

---

.github/dependabot.yml
.github/workflows/build-test.yml
Makefile
README.md
cmd/integration-test/integration-test.go
cmd/integration-test/library.go
integration_tests/run.sh
pkg/engine/hybrid/hybrid.go
pkg/engine/standard/standard.go
pkg/types/options.go

This PR adds
```go
package main
import (
"github.com/projectdiscovery/gologger"
"github.com/projectdiscovery/katana/pkg/engine/standard"
"github.com/projectdiscovery/katana/pkg/output"
"github.com/projectdiscovery/katana/pkg/types"
)
func main() {
options := &types.Options{
MaxDepth:     1,               // Maximum depth to crawl
FieldScope:   "rdn",           // Crawling Scope Field
BodyReadSize: 2 * 1024 * 1024, // Maximum response size to read
RateLimit:    150,             // Maximum requests to send per second
OnResult: func(result output.Result) { // Callback function to execute for result
gologger.Info().Msg(result.URL)
},
}
crawlerOptions, err := types.NewCrawlerOptions(options)
if err != nil {
gologger.Fatal().Msg(err.Error())
}
crawler, err := standard.New(crawlerOptions)
if err …
```

Add katana as lib

---

cmd/katana/main.go
go.sum
internal/runner/healthcheck.go
internal/runner/options.go
pkg/types/options.go

Adding self-diagnostic functionality

---

README.md
cmd/katana/main.go
internal/runner/options.go
pkg/engine/hybrid/hybrid.go
pkg/engine/standard/standard.go
pkg/output/error.go
pkg/output/options.go
pkg/output/output.go
pkg/output/result.go
pkg/types/crawler_options.go
pkg/types/options.go

```console
$ echo http://abcd | go run . -elog errors -v
$ cat errors
{"timestamp":"2023-01-10T00:16:14.318912+01:00","endpoint":"http://abcd","error":"GET http://abcd giving up after 2 attempts: Get \"http://abcd\": no address found for host"}
```
Closes #211

Adding support for error logs

---

Dockerfile

This change would build from source when building the Docker image instead of doing an install from GitHub. This should ensure the same version that is being released ends up in the Docker image with the correct tag, fixing issues like #275 
Fixes #275

Build from source when building Docker image

---

cmd/katana/main.go
go.mod
go.sum
internal/runner/executer.go
internal/runner/options.go
internal/runner/runner.go
pkg/engine/common/http.go
pkg/engine/hybrid/crawl.go
pkg/engine/hybrid/hybrid.go
pkg/engine/parser/files/robotstxt.go
pkg/engine/parser/files/sitemapxml.go
pkg/engine/standard/crawl.go
pkg/engine/standard/standard.go
pkg/output/custom_field.go
pkg/output/fields.go
pkg/output/output.go
pkg/output/responses.go
pkg/types/crawler_options.go

- Now log contains host/url in crawl warning/errors
- Improved Error logging using `utils/errors`
- removed deprecated `github.com/pkg/errors`
- Added debug mode support with env variable `DEBUG=1`
- Prints stacktrace of error if `DEBUG` variable is not empty
closes #168

improved logging

---

README.md

This helps clear up confusion between `rdn`, `fdqn` and `dn` by providing examples.

Add examples to rdn, fqdn, etc.

---

pkg/engine/common/http.go

Closes #170 
Example:
```console
$ go run . -proxy http://127.0.0.1:8080 -u https://site.com -d 5 -jc  -v
__        __
/_/\_\\_,_/\__/\_,_/_//_/\_,_/ v0.0.3
[script] https://site.com/static/111213/js/perf/stub.js
```

Setting max tls1.2 with burp proxy

---

pkg/utils/queue/queue.go

- consider a scenario of url is some icon or css url
- it does not have any more urls to traverse, at that time
- it was looping and checking if queue is nil or not for 10s.
- if we are passing multiple urls, then it consume all the CPU
- coz, infinite loop and using time.Now() in for loop.
- now, it will check after 1s.

Fix katana consuming all cpu

---

README.md
cmd/katana/main.go
pkg/engine/hybrid/hybrid.go
pkg/engine/standard/standard.go
pkg/types/options.go
pkg/utils/utils.go

https://baike.baidu.com/planet/talk?lemmaId=3407384
https://baike.baidu.com/planet/talk?lemmaId=3407385
https://baike.baidu.com/planet/talk?lemmaId=3407386
https://baike.baidu.com/planet/talk?lemmaId=......
closes #247

Ignore crawling same path with different query-param values

---

README.md

It'll cause the following err if not specified:
```[ERR] Could not crawl targets: unsupported strategy
[FTL] Failed to scan targets with katana. Error: unsupported strategy
exit status 1
```

Update lib example

---

README.md
cmd/katana/main.go
pkg/engine/hybrid/crawl.go
pkg/engine/standard/crawl.go
pkg/navigation/response.go
pkg/output/output.go
pkg/types/options.go
pkg/utils/formfields.go
pkg/utils/formfields_test.go

Added the following option to parse forms
```
-fx, -form-extraction        enable extraction of form, input, textarea & select elements
```
output format
```json
forms": [                                                                                                                                                                                                       
{                                                                                                                                                                                                              
"method": "POST",                                                                                                                                                                                            
"action": …
```

Adds option to parse form, input, textarea & select elements

---

pkg/engine/common/base.go
pkg/output/options.go
pkg/output/output.go
pkg/types/crawler_options.go

This PR fixes a bug in the output filter with extensions. Closes #480.
```
$ go run . -u https://blog.it-securityguard.com -jc -f ufile -em js
[INF] Current katana version v1.0.3-dev (development)
[INF] Started standard crawling for => https://blog.it-securityguard.com
https://blog.it-securityguard.com/wp-content/plugins/pdf-embedder/assets/js/min/all-pdfemb-min.js?ver=b82890d99bf14594a05514ba8096cd4d
https://blog.it-securityguard.com/\/blog.it-securityguard.com\/wp-content\/plugins\/pdf-embedder\/js\/pdfjs\/pdf.worker.min.js
https://blog.it-securityguard.com/wp-content/plugins/pdf-embedder/assets/js/ …
```

fix extension filter

---

README.md

Minor change to the README file:
The parameter to write the output in json is "-json**l**" as referenced in the beginning.

-jsonl parameter in README file

---

cmd/katana/main.go
pkg/engine/common/base.go
pkg/engine/common/http.go
pkg/types/options.go

This PR implements random TLS impersonate for standard http crawler. Hybrid crawling already support natively tls extension randomization.
Closes #136

Add random tls impersonate

---

pkg/engine/hybrid/crawl.go
pkg/engine/standard/crawl.go
pkg/utils/formfields.go
pkg/utils/formfields_test.go

Hi, i made some improvement to the form extraction feature.
CHANGES:
- action attributes get normalized to absolute urls
- missing method attributes get normalized to GET
- missing enctype attributes get normalized to application/x-www-form-urlencoded
i used the following page for testing
```html
<!DOCTYPE html>
<html>
<body>
<form action=https://abs.example.com></form>
<form action=//prel.example.com></form>
<form action=\\unc.example.com></form>
<form action=/root_rel></form>
<form action=path_rel></form>
<form></form>
</body>
</html>
```
result

[IMPROVEMENT] Normalization of action & method attributes in form extraction feature.

---

pkg/engine/parser/parser.go

Add missing ExtractRelativeEndpoints() in scriptJSFileRegexParser()

---

README.md
cmd/katana/main.go
pkg/utils/scope/scope.go

This feature is needed on cases where you have a initial website to recon, and you know that the company can use multiple base domains in its application.
For example, you can start crawling all sites of `*.company.com`, and then find mentions to `company-staging.io`. With this new commit, you can then add both hostnames to Katana's field scope by doing `-fs '(company-staging.io|company.com)'`.
It made a lot of sense to implement this on Katana for my automation, it may be useful to others.

added support for custom regex on field scope (-fs "[regex pattern]")

---

cmd/katana/main.go
pkg/engine/common/http.go
pkg/types/options.go

Added a new flag -dr, -disable-redirects which sets the http client to not follow redirects. 
Issue: #561 
Examples:
With following redirects enabled (default):
With following redirects disabled:

Add option to disable following redirects

---

pkg/engine/hybrid/crawl.go

None of the headers of XHR requests are outputted when performing headless crawls with the `-xhr` flag set:
```
> echo "https://projectdiscovery.io" | katana -silent -d 2 -jsonl -headless -xhr -cs "https://projectdiscovery.io" -ob -or -timeout 30 | jq ".response.xhr_requests"
...
[
{
"method": "OPTIONS",
"endpoint": "https://events.framer.com/anonymous"
},
{
"method": "POST",
"endpoint": "https://events.framer.com/anonymous",
"body": "[{\"source\":\"framer.site\",\"timestamp\":1697650690430,\"data\":{\"type\":\"track\",\"uuid\":\"a7dd37e7-62ca-459e-fb2a-0df5891948de\",\"event\":\"published_site_pageview\",\"referrer\":null,\"url\":\"https://projectdiscovery.io/requestdemo\",\"hostname\":\"projectdiscovery.io\",\"pathname\":\"/requestdemo\",\"hash\":null,\"search\":null,\"framerSiteId\":\"7 …
```

Patch: save correct headers for XHR requests

---

pkg/engine/common/base.go
pkg/engine/hybrid/crawl.go
pkg/engine/parser/parser.go
pkg/navigation/response.go

This fixes #610, where redirects are not followed when performing a katana crawl.
"Standard" crawl:
```
> echo "http://projectdiscovery.io" | katana -silent -d 2 -disable-redirects
http://projectdiscovery.io
https://projectdiscovery.io/
> echo "http://projectdiscovery.io" | katana -silent -d 2 -disable-redirects
http://projectdiscovery.io
```
"Headless" crawl:
```
> echo "http://projectdiscovery.io" | katana -silent -d 2 -disable-redirects -headless
https://projectdiscovery.io/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js
https://projectdiscovery.io/cdn-cgi/scripts/5c5dd728/cloudflare-static/'+e.replace(/
https://projectdiscovery.io/cdn-cgi/l/email-protection
http://projectdiscovery.io
https://projectdiscovery.io/
https://projectdiscovery.io/terms …
```

Patch: update crawling to not follow redirects when `-disable-redirects` is set

---

README.md
cmd/katana/main.go
internal/runner/options.go

```console
$ go run . -u https://remoteadvisor-east1.apple.com/ -hl --system-chrome -xhr-extraction -kf all -depth 2 -aff -s
breadth-first -iqp -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" -o 
a.json
[INF] Depth automatically set to 3 to accommodate the `--known-files` option (originally set to 2).
[INF] Current katana version v1.0.4 (latest)
[INF] Started headless crawling for => https://remoteadvisor-east1.apple.com/
https://remoteadvisor-east1.apple.com/api/
https://remoteadvisor-east1.apple.com/files/ …
```

auto increase depth when `-kf` is used

---

.gitignore
go.mod
go.sum
internal/runner/options.go
pkg/engine/parser/parser.go

```console
$ cat ~/.config/katana/form-config.yaml 
color: '#e66465'
password: katanaP@assw0rd1
phone: "2124567890"
placeholder: katana
$ go run . -u http://0.0.0.0:8000 -aff -v
[INF] Current katana version v1.0.4 (latest)
[INF] Started standard crawling for => http://0.0.0.0:8000
[GET] http://0.0.0.0:8000
[form] [POST] http://0.0.0.0:8000/submit [email=]
^C[INF] - Ctrl+C pressed in Terminal
[INF] Creating resume file: /home/vscode/.config/katana/resume-clndk6s3j6ee0m16gv90.cfg
```
```
http://0.0.0.0:8000/submit
POST /submit HTTP/1.1
Host: 0.0.0.0:8000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS …
```

send field with empty value

---

cmd/katana/main.go
go.mod
go.sum
internal/runner/executer.go
internal/runner/runner.go
pkg/types/crawler_options.go
pkg/types/options.go

Closes #719
```console
$ go run . -exclude 'cdn,private-ips,http://*scanme.sh,443,1.0.0.0/24,https://www.hackerone.com' -u 'http://scanme.sh,127.0.0.1,scanme.sh:443,projectdiscovery.io,example.com,https://www.hackerone.com'
[INF] Current katana version v1.0.5 (latest)
[INF] Skipping excluded host http://scanme.sh
[INF] Skipping excluded host 127.0.0.1
[INF] Skipping excluded host scanme.sh:443
[INF] Skipping excluded host https://www.hackerone.com
[INF] Started standard crawling for => https://projectdiscovery.io
[INF] Started standard crawling for => https://example.com
https://projectdiscovery.io …
```

introduce exclude flag

---

pkg/engine/common/base.go
pkg/output/output.go
pkg/types/crawler_options.go

Closes #716
```go
package main
import (
"math"
"github.com/projectdiscovery/gologger"
"github.com/projectdiscovery/gologger/levels"
"github.com/projectdiscovery/katana/pkg/engine/standard"
"github.com/projectdiscovery/katana/pkg/output"
"github.com/projectdiscovery/katana/pkg/types"
)
func main() {
gologger.DefaultLogger.SetMaxLevel(levels.LevelSilent)
options := &types.Options{
MaxDepth:         3,           // Maximum depth to crawl
FieldScope:       "rdn",       // Crawling Scope Field
BodyReadSize:     math.MaxInt, // Maximum response size to read
Timeout:          10,          // Timeout is the time to wait for request in seconds
Concurrency:      10,          // Concurrency is the number of concurrent crawling goroutines
OutputMatchRegex: []string{"policies"},
Parallelism:      10, …
```

fix filter and match functionality in lib

---

pkg/engine/common/base.go

Closes #529
before:
```console
$ go run . -u www.apple.com -kf all -v
[INF] Current katana version v1.0.5 (latest)
[INF] Started standard crawling for => https://www.apple.com
[file] [GET] https://www.apple.com/wtgh/re/
[file] [GET] https://www.apple.com/working-with-apple-services/
[file] [GET] https://www.apple.com/watch/close-your-rings/
[file] [GET] https://www.apple.com/usergroups/
[file] [GET] https://www.apple.com/watch/battery/
[file] [GET] https://www.apple.com/watch/cellular/
[file] [GET] https://www.apple.com/watch/
[file] [GET] https://www.apple.com/watch/why-apple-watch/
[file] [GET] …
```

skip if the maximum depth is exceeded

---

README.md

* Update README.md - Added missed flag of new feature ( `-e` ) introduced via [katana v1.1.0](https://github.com/projectdiscovery/katana/releases/tag/v1.1.0)

Added Missed Flag of New Feature ( -e ) in README.md

---

pkg/engine/hybrid/hybrid.go

Enable leakless

---

cmd/katana/main.go
go.mod
go.sum

Deduplicate lines in files

---

pkg/engine/common/base.go
pkg/navigation/request.go

skip scope validation for initial host

---

pkg/navigation/response.go

Closes #922
```console
$ go run . -u scanme.sh -j | jq
[INF] Current katana version v1.1.0 (latest)
[INF] Started standard crawling for => https://scanme.sh
{
"timestamp": "2024-06-07T13:49:57.458764+03:00",
"request": {
"method": "GET",
"endpoint": "https://scanme.sh",
"raw": "GET / HTTP/1.1\r\nHost: scanme.sh\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36\r\nAccept-Encoding: gzip\r\n\r\n"
},
"response": {
"status_code": 200,
"headers": {
"content-type": "text/plain; charset=utf-8",
"date": "Fri, 07 Jun 2024 …
```

fix header marshalling

---

internal/runner/options.go
pkg/engine/hybrid/crawl.go

Closes  #876
```console
```console
$ go run . -u http://testphp.vulnweb.com -hl -aff -j -o test.json
...
$ grep -r 'method":"POST"' test.json | grep -o '"raw":.*' | cut -c 1-50
"raw":"POST /search.php?test=query HTTP/1.1\r\nHos
"raw":"POST /search.php?test=query HTTP/1.1\r\nHos
"raw":"POST /userinfo.php HTTP/1.1\r\nHost: testph
"raw":"POST /userinfo.php HTTP/1.1\r\nHost: testph
"raw":"POST /secured/newuser.php HTTP/1.1\r\nHost:
"raw":"POST /secured/newuser.php HTTP/1.1\r\nHost:
"raw":"POST /guestbook.php HTTP/1.1\r\nHost: testp
"raw":"POST /guestbook.php HTTP/1.1\r\nHost: testp
```

disable headless auto form filling

---

pkg/engine/hybrid/crawl.go

Based on #930
We crawl an endpoint
The request sent by the hybrid engine is according to the proxy : 
Current output: 
Based on Custom Headers and GO httpreq only
With my PR:
Based on the hijacked request detected by the hybrid engine

New way to add headers for hybrid request output

---

pkg/engine/parser/parser.go
pkg/utils/formfill.go
pkg/utils/formfill_test.go
pkg/utils/maps.go
pkg/utils/maps_test.go

I tried to add the detection of textearea and select in a form, respecting what was already implemented. This is the first time I've worked on a GO project. I don't know whether I'm using best practices and whether my proposal is as modular as possible. Don't hesitate to point out any pieces of code that seem badly written. 
PR based on the issue #456

Add AutoFillFormSuggestion for select,textarea in form

---

pkg/engine/hybrid/hybrid.go

When the katana process exits, rod will automatically kill the browser process. (https://github.com/go-rod/rod/issues/550#issuecomment-1064650720)
Moreover, when using non-headless mode (`-sb`), even if `Ctrl-c` is pressed, the katana will hang on `browser.close()` until the scraping is complete, preventing the process from terminating.
Close #978

no need for browser.close()

---

pkg/engine/parser/parser.go
pkg/engine/parser/parser_test.go

close #1023
At the moment, it just extracts endpoints from `hx-*` attributes. Next, we could think about adding features like automatic parameter filling.

Add a parser to get endpoints from htmx attributes

---

Dockerfile

Build Error --
github.com/projectdiscovery/fastdialer/fastdialer/metafiles
/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.0.64/fastdialer/metafiles/shared.go:49:21: undefined: sync.OnceFunc
/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.0.64/fastdialer/metafiles/shared.go:73:19: undefined: sync.OnceFunc
note: module requires Go 1.21
Update Docker file with latest golang and GOMODULE=on. 
Fix Build path to main.go. 
Thanks !!

update 1.23.1-alpine3.20 + GO111MODULE=on

---

pkg/output/fields.go

Closes #1025
```console
$ go run . -u http://localhost:8000/test.html -f email,h2,title
[INF] Current katana version v1.1.0 (latest)
[INF] Started standard crawling for => http://localhost:8000/test.html
admin@example.com
testingaaaa
Test Page
```

fix custom field duplicate output

---

pkg/engine/hybrid/crawl.go
pkg/engine/standard/crawl.go
pkg/navigation/response.go

add content len field

---

.github/workflows/compat-checks.yaml

Closes #1327 
Skip release test since we use custom GoReleaser configuration (== not located in `$WORKSPACE/.goreleaser.yaml`).

ci(compat-checks): disable release test

---

cmd/katana/main.go
internal/runner/executer.go
pkg/engine/common/base.go
pkg/types/options.go
pkg/utils/utils.go
pkg/utils/utils_test.go

closes https://github.com/projectdiscovery/katana/issues/867
```console
$ go run . -u https://scanme.sh/test/path/to/file.html -pc   
[INF] Current katana version v1.1.3 (latest)
[INF] Started standard crawling for => https://scanme.sh/test
[INF] Started standard crawling for => https://scanme.sh/test/path/to/file.html
[INF] Started standard crawling for => https://scanme.sh/test/path
[INF] Started standard crawling for => https://scanme.sh/test/path/to
https://scanme.sh/test/path/to/file.html
https://scanme.sh/test/path
https://scanme.sh/test/path/to
https://scanme.sh/test
```

introduce path climb to discover parent paths to crawl
