projectdiscovery/katana

.github/workflows/dockerhub-push.yml
Reference - https://github.com/projectdiscovery/katana/actions/runs/3444061486/jobs/5746257142
=> Removing linux/arm - Missing chrome package

SECURITY.md, pkg/engine/hybrid/crawl.go
=> Fixes #194

README.md
=> Adding chrome requirements recommended setup for ubuntu

README.md, cmd/katana/main.go, internal/runner/options.go, pkg/output/options.go, pkg/output/output.go, pkg/types/crawler_options.go, pkg/types/options.go
```console
./katana -u https://tesla.com -mr 'https://shop\.tesla\.com/*' -ns
/_/\_\\_,_/\__/\_,_/_//_/\_,_/ v0.0.4-dev							 
https://shop.tesla.com/en_ae?redirect=no
https://shop.tesla.com/fr_be?redirect=no
https://shop.tesla.com/fr_lu?redirect=no 
https://shop.tesla.com/en_dk?tesref=true
https://shop.tesla.com/en_fi?tesref=true
https://shop.tesla.com/zh_tw?tesref=true
https://shop.tesla.com/cs_cz?redirect=no
https://shop.tesla.com?tesref=true
https://shop.tesla.com/
https://shop.tesla.com/category/charging
https://shop.tesla.com/category/vehicle-accessories
https://shop.tesla.com/category/apparel
https://shop.tesla.com/category/lifestyle …
```
=> Add match and filter options

pkg/engine/common/base.go, pkg/engine/common/error.go
```console
$ katana -do -u http://testphp.vulnweb.com
...
http://www.acunetix.com
...
```
=> Fixing "do" functionality

README.md, cmd/integration-test/library.go
=> Update readme to reflect result struct change

README.md
=> Add document for header

.github/release.yml, go.mod, go.sum
https://github.com/projectdiscovery/katana/pull/511 was erroneusly pushed to main so `dev` needs to be rebased with it
=> Aligning main <=> dev

Dockerfile
=> add build deps for `go-tree-sitter` -> `tree-sitter`

README.md
- add syntax highlight for Golang sample code part
=> README syntax highlight

README.md
=> update README lib example

pkg/engine/hybrid/crawl.go
Closes https://github.com/projectdiscovery/katana/issues/734
=> Fixing Hybrid Redirect

internal/runner/options.go, internal/runner/runner.go, pkg/types/crawler_options.go
=> fix lib log config issue

pkg/engine/standard/crawl.go
=> Fix ignoring host header

.goreleaser/windows.yml, pkg/engine/parser/parser_generic.go, pkg/engine/parser/parser_nojs.go, pkg/utils/jsluice.go, pkg/utils/jsluice_test.go
=> Adding windows generic

.github/dependabot.yml, Dockerfile
When trying to build via the `Dockerfile`, received an error due to versions.  Bumping versions to a supported version which works.
=> Updating Dockerfile to recent Golang and Alpine images

internal/runner/runner.go, pkg/types/crawler_options.go, pkg/types/options.go
=> fix cli log config issue

pkg/engine/hybrid/hybrid.go
=> ignore default paths if -scp is provided

README.md
=> docs(README): update installation usage

pkg/utils/formfields.go
=> fix form extraction: action parsing

pkg/output/responses.go
Closes https://github.com/projectdiscovery/katana/issues/1228
=> make dir name os agnostic

go.mod, go.sum, pkg/output/output.go
Closes https://github.com/projectdiscovery/katana/issues/1278
=> fix dsl matcher

.github/workflows/release-test.yml, .goreleaser/linux.yml, .goreleaser/mac.yml, .goreleaser/windows.yml
closes https://github.com/projectdiscovery/katana/issues/1289
=> update release test action

README.md, cmd/katana/main.go, go.mod, go.sum, pkg/navigation/request.go, pkg/output/custom_field.go, pkg/output/format_json.go, pkg/output/format_template.go, pkg/output/options.go, pkg/output/output.go, pkg/types/crawler_options.go, pkg/types/options.go
Close #1196 
Close #1182 
Proof:
```console
$ go run cmd/katana/main.go -silent -u https://www.google.com/appserve/security-bugs/m2/new -ot "{{email}} - {{url}}"
for.someone.else@gmail.com - https://www.google.com/appserve/security-bugs/m2/new
robert@broofa.com - https://www.google.com/xjs/_/js/k=xjs.hd.id.dGr1WnNk0mU.es5.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAARAAAAAAAIAAAAEAAABAAAAAAIgAEgQAACAAAAIAJAACAwAAAAAAAgAAAgACAR5kCAAEJAAAAAAAACACAAB8BAAAAAAQAAAAAIAAAAAAAAFAAAAAAAEAAAAAAAIAAAIAABAAAAAAAAAAAACAAAAA9AAAAAAAAAAAAACAAAADAYMQACAAAAAAAAPQAEDwAQwoKAAAAAAAAAAAAAAAgQIJgLiSgIAABAAAAAAAAAAAAAAAAAIg0saAB/d=1/ed=1/dg=3/br=1/rs=ACT90oEyrn00_5ziGeuqVjgXzuV-MikkAw/ee=ALeJib:B8gLwd;AfeaP:TkrAjf;BMxAGc:E5bFse;BgS6mb:fidj5d;BjwMce:cXX2Wb;CxXAWb:YyRLvc;DMzTfb:fNTHad;DULqB:RKfG5c;Dkk6 …
```
=> feat: add `-output-template` option

pkg/engine/common/base.go, pkg/types/options.go
closes https://github.com/projectdiscovery/katana/issues/1264
=> introduce onskipurl to allow more control over SDK behavior
